### ISSUE TITLE
Transfer or fork markets app into bisq-network org

### ISSUE THREAD

**Issue by cbeams** [bitsquare/pm#20]
The repository at dan-da/bitsquare_market should be transferred to bisq-network/markets. I've reached out to @dan-da about this. Certain tasks are pending our ability to make changes to the markets app, including dan-da/bitsquare_market#7 and bisq-network/numbers#1. We'll wait for @dan-da's response for another day or so, but will fork soon thereafter.

**Comment by dan-da** [comment]
Yes, please go ahead and fork.  I think that is best for preserving historical record and is most in spirit of git decentralized methodologies.   Then we only need change the .git/config entry on the market server and the new fork becomes the "official" repo that is pulled from for deployments.

**Comment by cbeams** [comment]
Closing as complete. The new repository is available at https://github.com/bisq-network/markets. See bisq-network/dao#30 for details.
