### ISSUE TITLE
Bridge #bitsquare Freenode IRC channel into Slack

### ISSUE THREAD

**Issue by cbeams** [bitsquare/pm#4]
It would be good to monitor what's going on in IRC from Slack. A read-only mirror would be sufficient, bi-directional communication would be even better.

Note that Slack offers an IRC gateway, i.e. a way to access Slack itself via IRC, but this is not what's being discussed here.

A few links from a brief search about the topic:

 - [ekmartin/slack-irc](https://github.com/ekmartin/slack-irc) looks like a popular Slack bot-based solution. Requires someone to set up and run the bot.
 - Sameroom.io offers [IRC->Slack mirroring as a service](https://sameroom.io/blog/mirror-freenode-channels-in-slack/), but the free tier is unusably restricted at 5 messages/mo and the next tier up is surprisingly expensive at $49/mo.
 - Cloudpipes has what looks like a pretty sophisticated [bi-directional IRC-Slack bridge](https://www.cloudpipes.com/integrations/irc/slack), but we'd again be looking at $49/mo for that service

Comments welcome, and if someone wants to take the time to set up one of these bots, etc, it would be appreciated.

/cc @dan-da @mrosseel

**Comment by mrosseel** [comment]
Agreed this would be a good thing to have, of course it's only one piece in the wider goal of aligning all our communication channels. For that purpose I will document here how I see it, discussion welcome of course.

## Intro
One way to go, which marries the open source/privacy oriented nature of this community without sacrificing usage of best in class tools, is the following: use a matrix room to bridge all communication channels. This room uses existing bridges to irc, telegram, ... and a bridge to slack.

*Note that there already is a 'bitsquare' room on matrix, where matrix users can talk, and which is bridged with irc (2-way).*

## Listing of channels

* Matrix
  * bisq-general room, bridging bisq-general on irc, bisq group on telegram and bisq-general on slack
  * bisq-dev room, bridging bisq-dev on irc and bisq-dev on slack
* IRC
  * bisq-general
  * bisq-dev
* Slack
  * bisq-general
  * bisq-dev
  * all other channels necessary to manage the project. These are not mirrored anywhere, and can be public or private
* Telegram
  * bisq group

## Open questions

* which bridges to choose (there are multiple IRC bridges, 2 for slack, ... )
* Currently we use the matrix central server for our rooms and irc bridges. Is it possible (and do we want) to continue using this server when adding our slack and telegram bridges?

## References

* List of matrix bridges: https://matrix.org/docs/projects/try-matrix-now.html    (scroll down to Application Services)

/cc @Emzy

**Comment by mrosseel** [comment]
This issue can probably be closed, since there's now a bridging between slack#community, irc#bisq, telegram#bitsquare and matrix#bisq. Some fine-tuning might still be needed, but it's there and it's working.

**Comment by cbeams** [comment]
Agreed, thanks. Closing as complete.
